apiVersion: v1
kind: Secret
metadata:
  name: auth-firebase-secret
  namespace: backend
type: Opaque
stringData:
  graduation-project-3c67f-firebase-adminsdk-fbsvc-b88880ea28.json: |
    {
      "type": "service_account",
      "project_id": "graduation-project-3c67f",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "",
      "universe_domain": "googleapis.com"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-firebase-secret
  namespace: backend
type: Opaque
stringData:
  firebase-adminsdk.json: |
    {
      "type": "service_account",
      "project_id": "graduation-project-3c67f",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "",
      "universe_domain": "googleapis.com"
    }

# mohamedelsawyy    