apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: backend
  labels:
    app: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: mohamedelsawyy/reportservice:dbc472b
          ports:
            - containerPort: 8080  
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Jwt__Issuer
              value: "WAHAKUN.Auth"
            - name: Jwt__Audience
              value: "WAHAKUN.Client"
            - name: Jwt__Expiry
              value: "60"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: password
            - name: ConnectionStrings__SQLConnection
              value: "Server=sql-server.data-services.svc.cluster.local,1433;Database=ReportDb;User Id=$(DB_USER);Password=$(DB_PASSWORD);TrustServerCertificate=True;Encrypt=True;"
            - name: ConnectionStrings__AuthSqlConnection
              value: "Server=sql-server.data-services.svc.cluster.local,1433;Database=AuthDb;User Id=$(DB_USER);Password=$(DB_PASSWORD);TrustServerCertificate=True;Encrypt=True;"

            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: signing-key
            - name: Services__Storage__BaseUrl
              value: "http://media-storage-service.backend.svc.cluster.local"
            - name: Services__AI__BaseUrl
              value: "http://vision-ai-api-service.backend.svc.cluster.local"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /swagger
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /swagger
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: backend
spec:
  selector:
    app: report
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: report-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: report-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 0