apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wahakun-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/waha-kun-Japanese-Project/k8s-definitions-files.git
    targetRevision: main
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true