apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq
spec:
  containers:
   - name: rabbitmq
     image: rabbitmq:4.0-management
     ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
     env:
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "admin"
